### ISSUE TITLE
Example prompt has OpenAI as the model

### ISSUE THREAD

**Issue by sepiatone** [hinthornw/promptimizer#4]
The prompt in the example to demonstrate `promptim` usage has OpenAI as the model. This causes a API key error.

Perhaps change the example to use an OpenAI model  or change the prompt used in the example to use an Anthropic model.

![Screenshot 2024-11-08 at 13-02-06 LangSmith](https://github.com/user-attachments/assets/6862f580-872c-4071-b190-c3ea30cf3863)

**Comment by hinthornw** [comment]
Good callout

**Comment by hinthornw** [comment]
Fixed
